version: '3.3'

services:
  plumber-proxy:
    image: krapi0314/plumber
    container_name: plumber
    command:
      - "--backends"
      - "http://server-1:80,http://server-2:80,http://server-3:80"
    ports:
      - "80:80"
  server-1:
    image: traefik/whoami
    hostname: server-1
  server-2:
    image: traefik/whoami
    hostname: server-2
  server-3:
    image: traefik/whoami
    hostname: server-3

networks:
  plumber: