version: '3.3'

services:
#  plumber-proxy:
#    image: krapi0314/plumber
#    container_name: plumber
#    command:
#      - "--backends"
#      - "http://server-1:80,http://server-2:80,http://server-3:80"
#    ports:
#      - "80:80"
  yorkie-1:
    image: 'yorkieteam/yorkie:latest'
    hostname: 'yorkie-1'
    command: ['server', '--mongo-connection-uri', 'mongodb://mongo:27017']
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  yorkie-2:
    image: 'yorkieteam/yorkie:latest'
    hostname: 'yorkie-2'
    command: ['server', '--mongo-connection-uri', 'mongodb://mongo:27017']
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - mongo
  yorkie-3:
    image: 'yorkieteam/yorkie:latest'
    hostname: 'yorkie-3'
    command: ['server', '--mongo-connection-uri', 'mongodb://mongo:27017']
    restart: always
    ports:
      - '8082:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    restart: always
    ports:
      - '27017:27017'

networks:
  plumber: